---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .MpsControlDaemonNamespace }}
  name: {{ .MpsControlDaemonName }}
  labels:
    app: {{ .MpsControlDaemonName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .MpsControlDaemonName }}
  template:
    metadata:
      labels:
        app: {{ .MpsControlDaemonName }}
    spec:
      nodeName: {{ .NodeName }}
      hostPID: true
      containers:
      - name: mps-control-daemon
        image: {{ .MpsImageName }}
        securityContext:
          privileged: true
        command: [sh, -c]
        args:
        - |-
          set -e
          rm -f /driver-root/var/log/nvidia-mps/startup.log

          if [ -x /driver-root/bin/sh ] || [ -x /driver-root/usr/bin/sh ]; then
            # Use chroot to avoid library mismatch between container and host when driver root is / (default value)
            RUN="chroot /driver-root sh -c"
          else
            # No shell in driver root (e.g. GKE COS): run directly with PATH/LD_LIBRARY_PATH
            export PATH="/driver-root/usr/bin:/driver-root/bin:/driver-root/usr/local/bin:$PATH"
            export LD_LIBRARY_PATH="/driver-root/lib64:/driver-root/lib:/driver-root/usr/lib64:/driver-root/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
            RUN="sh -c"

            # Point MPS to mounted paths (not set in Deployment spec as for chroot approach /driver-root/... paths don't exist inside chroot)
            export CUDA_MPS_PIPE_DIRECTORY=/driver-root/tmp/nvidia-mps
            export CUDA_MPS_LOG_DIRECTORY=/driver-root/var/log/nvidia-mps
          fi

          $RUN "nvidia-cuda-mps-control -d"
          {{- if .DefaultActiveThreadPercentage }}
          $RUN "echo set_default_active_thread_percentage {{.DefaultActiveThreadPercentage}} | nvidia-cuda-mps-control"
          {{- end}}
          {{- range $id, $limit := .DefaultPinnedDeviceMemoryLimits }}
          $RUN "echo set_default_device_pinned_mem_limit {{ $id }} {{ $limit }} | nvidia-cuda-mps-control"
          {{- end}}

          echo "startup complete" > /driver-root/var/log/nvidia-mps/startup.log

          tail -n +1 -f /driver-root/var/log/nvidia-mps/control.log
        startupProbe:
          exec:
            command:
            - cat
            - /driver-root/var/log/nvidia-mps/startup.log
          initialDelaySeconds: 1
          periodSeconds: 1
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "{{ .CUDA_VISIBLE_DEVICES }}"
        {{- if .FeatureGates }}
        # Feature gates (includes both project-specific and logging features)
        - name: FEATURE_GATES
          value: "{{ range $key, $value := .FeatureGates }}{{ $key }}={{ $value }},{{ end }}"
        {{- end }}
        volumeMounts:
        - name: driver-root
          mountPath: /driver-root
        - name: mps-shm-directory
          mountPath: /driver-root/dev/shm
        - name: mps-pipe-directory
          mountPath: /driver-root/tmp/nvidia-mps
        - name: mps-log-directory
          mountPath: /driver-root/var/log/nvidia-mps
      volumes:
      - name: driver-root
        hostPath:
          path: {{ .NvidiaDriverRoot }}
      - name: mps-shm-directory
        hostPath:
          path: {{ .MpsShmDirectory }}
      - name: mps-pipe-directory
        hostPath:
          path: {{ .MpsPipeDirectory }}
      - name: mps-log-directory
        hostPath:
          path: {{ .MpsLogDirectory }}
